.circleci/config.yml
This changeset adds a Docker image as all CircleCI builds require an executor type.
=> Add Docker image to CircleCI config

.circleci/config.yml
This changeset fixes the Docker image to use the latest release of Node.js with our builds and greatly simplifies the setup of the build process.
A huge h/t to @jeremiak for all of the help and feedback!
=> Fix Docker image reference and build setup

.circleci/config.yml
This changeset removes the global fractal install instruction as we should not need it.  It is already defined in package.json.
=> Remove global fractal install

.circleci/config.yml
This changeset adds a missing line to configure the PATH environment variable so that the CF CLI tool can be found.
=> Add missing line from deploy step

README.md
While trying to run the pattern library locally, I ran into an error that may happen again in the future. 
Since `fec-cms` is a dependency in this repo, any changes to styles there will be picked up by this repo, and may have discrepancies. This adds instructions for troubleshooting in that scenario. 
cc @johnnyporkchops & @patphongs
=> Add debugging for missing style errors to repo README

package.json
Moment version from 2.17 to 2.19.3 to match CMS
Gemnasium alert: https://gemnasium.com/github.com/fecgov/fec-pattern-library/alerts#alert-7249688
=> Update moment version per Gemnasium alert

components/02-components/buttons/01-basic/basic.html, components/02-components/buttons/02-buttons-with-icons/buttons-with-icons.html, components/02-components/buttons/03-sizes/sizes.html, components/02-components/filters/04-toggle-button/01-horizontal/horizontal.html, fractal.js, static/js/init.js
- Updates the button component based on criteria set in #57 
- Basic: Remove active state. The active state will be shown through the toggle component
- Basic: Add more spacing between buttons so that they don't look so much like toggles
- Icons: Show each button in just one color—color changes can be determined by the basic tab, and this will cut down clutter
- Icons: Add dropdown buttons. These examples were missing from the components
- Sizes: Remove the colored background slab to be consistent
- Adds additional toggle button examples discovered during research
- If #54 is merged before this PR, redirect this toward the master branch and any merge conflicts will need to be resolved.
- The "dropdown" functionality does not work in the examples I included of dropdown buttons with icons, …
=> Update button component previews

components/02-components/tables/01-simple-table/README.md, components/02-components/tables/01-simple-table/simple-table.html, components/02-components/tables/02-dense-table/README.md, components/02-components/tables/02-dense-table/dense-table.config.json, components/02-components/tables/02-dense-table/dense-table.html, components/02-components/tables/03-custom-table/README.md, components/02-components/tables/03-custom-table/custom-table.config.json, components/02-components/tables/03-custom-table/custom-table.html, components/02-components/tables/04-chart-table/README.md, components/02-components/tables/04-chart-table/chart-table.config.json, components/02-components/tables/04-chart-table/chart-table.html, components/02-components/tables/05-balance-sheet-table/README.md, components/02-components/tables/05-balance-sheet-table/balance-sheet-table.config.json, components/02-components/tables/05-balance-sheet-table/balance-sheet-table.html, components/02-components/tables/06-data-table/README.md, components/02-components/tables/06-data-table/data-table.config.json, components/02-components/tables/06-data-table/data-table.html
Updates table component based on audit in #67
Adds a more complete set of the table styles in use across the site. Includes examples and first draft notes about each.
- These components were especially large to copy over as HTML, and I'm not the most familiar with building them. I'd love help looking out for pieces of the code that aren't relevant and can be removed
- If there is a simple fix to get the panels to work on the data table component, that would be rad! If not, it can be a separate issue.
- ![screen shot 2018-03-07 at 1 17 11 am](https://user-images.githubusercontent.com/11636908/37076592-4dce1c30-21a5-11e8-8e49-a13baa81c8d2.png)
=> Update and add table components

components/02-components/figures/README.md, components/02-components/figures/figures.html
- Add two visually detailed examples for Figures component #62
=> Add examples to Figures

components/02-components/banner/banner.html
- Addresses #70 
It was determined that the blue banner component should be removed from the pattern library since this is a unique banner in staging, dev, and feature that would only be used to indicate which environment you are in.
=> Removed blue banner component

components/02-components/accordions/README.md, components/02-components/breadcrumbs/README.md, components/02-components/buttons/01-basic/README.md, components/02-components/filter-tags/README.md, components/02-components/filters/01-checkboxes/01-multiple/README.md, components/02-components/filters/02-radio-buttons/README.md, components/02-components/filters/03-dropdowns/01-single-select/README.md, components/02-components/filters/03-dropdowns/02-multi-select/README.md, components/02-components/filters/03-dropdowns/03-multi-select-with-suggestions/README.md, components/02-components/filters/04-toggle-button/01-horizontal/README.md, components/02-components/filters/04-toggle-button/02-vertical/README.md, components/02-components/filters/06-range/02-range-limited/README.md, components/02-components/filters/07-search/01-type-ahead-only/README.md, components/02-components/filters/07-search/02-type-ahead-and-free-text/README.md, components/02-components/filters/07-search/03-free-text-only/README.md, components/02-components/footer/README.md, components/02-components/header/README.md, components/02-components/heroes/README.md, components/02-components/loading-overlay/README.md, components/02-components/messages/01-message-sizes/README.md, components/02-components/messages/02-message-info/README.md, components/02-components/messages/03-message-success/README.md, components/02-components/messages/04-message-alert/README.md, components/02-components/messages/05-message-error/README.md, components/02-components/messages/06-message-no-results/README.md, components/02-components/secondary-navigation/01-side-navigation/README.md, components/02-components/tables/01-simple-table/README.md
- Restyles guidance from the U.S. Web Design System 🇺🇸 so that it's more obvious that the guidance has been copied over directly instead of rewritten. It does this by using blockquote styling, and by rewriting the headline.
- Connects TONS of design history to each component by adding GitHub issues to each 🕵️‍♀️ . This should make it easier for future design archeologists to find the history and intention behind research and interaction decisions.
**Before:**
**After:**
=> Style USWDS resources better and add GitHub history to components

components/01-basics/_colors.html
This adds color pairings from this issue: https://github.com/fecgov/fec-pattern-library/issues/39
This PR replaces this old PR https://github.com/fecgov/fec-pattern-library/pull/44. Check old PR for comments that should be fixed in this new PR.
=> Adds color pairing: text and icons section

components/02-components/feed/01-single-category/README.md, components/02-components/feed/01-single-category/single-category.config.json, components/02-components/feed/01-single-category/single-category.html, components/02-components/feed/02-multiple-category/README.md, components/02-components/feed/02-multiple-category/multiple-category.config.json, components/02-components/feed/02-multiple-category/multiple-category.html
Adds the existing post component from the site into the pattern library. I've named this component "Feed" instead of "Post" because the feed is what we've been calling a collection of posts.
=> Add feed component

components/01-basics/_collection-page.html, components/01-basics/_commissioner-page.html, components/01-basics/_custom-page.html, components/01-basics/_document-feed-page.html, components/01-basics/_meeting-page.html, components/01-basics/_reporting-example-page.html, components/01-basics/_reports-landing-page.html, components/01-basics/_resource-page.html, components/01-basics/_update-pages.html, documentation/06-page-layouts/collection-page.md, documentation/06-page-layouts/commissioner-page.md, documentation/06-page-layouts/custom-page.md, documentation/06-page-layouts/document-feed-page.md, documentation/06-page-layouts/meeting-page.md, documentation/06-page-layouts/reporting-example-page.md, documentation/06-page-layouts/reports-landing-page.md, documentation/06-page-layouts/resource-page.md, documentation/06-page-layouts/update-pages.md
- Addresses #106
Previously, the iframe sandbox property would not allow external links to break out of the frame. This 
- Adds the `allow-popups` directive to each iframe sandbox 
- Adds the `target="_blank"` to each link telling it to open in a new tab
that will let the pages open these links in a new browser tab
This PR also includes a change to format the "Update page" example links to be the same format as other links with descriptions.
**Link behavior**
_not sure why the cursor is huge...sorry!_
**Link formatting**
_Before_
_After_
=> Fix links in page template examples

gulpfile.js, package-lock.json, package.json
- Addresses #117 and #116 to fix vulnerabilities
- Updates the `package-lock` file to update supdependencies
- Upgraded `gulp.js` and the `gulpfile` syntax
=> Run npm audit to update dependencies in package-lock file

components/02-components/filters/02-radio-buttons/README.md, package-lock.json, package.json, static/scss/_icon-classes.scss
update radio button selected-state. This was changed in fec-cms PR [#3014](https://github.com/fecgov/fec-cms/pull/3014), Issue [#2950](https://github.com/fecgov/fec-cms/issues/2950)
- Addresses #140 
Update node_modules to get the new radio button styles
Edit Read.Me for radio button 
Update package.json and package-lock.json
How to Test:
-  Checkout branch
-  npm install
-  npm run build
-  npm run start
- Check Components > Filters > Radio Buttons to confirm that the slected state now looks like this:
=> Update radio-button selected-state

package-lock.json, package.json
- Resolves #3698 
_Upgrades jquery to 3.5.1 and remediates XSS vulnerabilities._
See jquery docs on what was released for 3.5.1: https://blog.jquery.com/2020/05/04/jquery-3-5-1-released-fixing-a-regression/
Upgraded jQuery from 3.4.1 to 3.5.1
modified: ../package-lock.json
modified: ../package.json
- `npm i`
- `npm run build`
- `npm run start`
- Spot check pages that use jquery
____
=> upgrade to jquery 3.5.1

.circleci/config.yml, bin/cf_deploy.sh
- Addresses #169
**Deploy task changes:**
- With cf cli version 7, `cf api <endpoint>` logs you out - this is a known issue: https://github.com/cloudfoundry/cli/issues/2075. Only set the endpoint if `deploy` task `--login True` (used for CircleCI)
List general components of the application that this PR will affect:
-  Deploys
- Example build: https://app.circleci.com/pipelines/github/fecgov/fec-pattern-library/26/workflows/6b254a3b-142a-44e5-9bf1-23273097faa3
**Through CircleCI**
- Make your own copy of this branch (please don't commit to this branch)
- Modify the branch here to be your branch name:
https://github.com/fecgov/fec-pattern-library/blob/5abf0a22eceddc851dde5dae8e2315f69c6d7038/.circleci/config.yml#L76-L81
- Push to Github, make sure build works
**Locally:**
- Install cf cli …
=> Update cf cli to version 7

.circleci/config.yml
- Addresses #175 
Remove unused autopilot plugin
One approval requested, thanks!
**Through CircleCI**
- Make your own copy of this branch (please don't commit to this branch :))
- Modify the branch on line 81 to be your branch name (`feature/175-remove-autopilot`):
https://github.com/fecgov/fec-pattern-library/blob/5abf0a22eceddc851dde5dae8e2315f69c6d7038/.circleci/config.yml#L76-L81
- Push to Github, make sure build works
=> Remove unused autopilot plugin

package-lock.json, package.json
- Resolves #188 
Upgrades moment to 2.29.2 to fix Directory Traversal vulnerability
1-2 devs
Related PRs against other branches:
FEC-CMS https://github.com/fecgov/fec-cms/pull/5155
- Note which versions of Node and npm are currently in use (`nvm ls` and `npm -v`) 
- `nvm use 10.16.0` and `npm i -g npm@6.14.8`
- Pull the branch
- rm -rf node_modules
- npm i
- npm run build 
- npm run start
*Thanks @rfultz for the feedback/improvements of the how to test section!
=> 188-upgrade moment

package.json
- Addresses #192 
Upgrades moment to 2.29.4 to fix Regular Expression Denial of Service (ReDoS) 
1-2 devs
- Note which versions of Node and npm are currently in use (`nvm ls` and `npm -v`) 
- `nvm use 10.16.0` and `npm i -g npm@6.14.8`   (I will put in an issue to upgrade NPM versions because these are no longer compatible with snyk CLI)
- Pull the branch
- rm -rf node_modules
- npm i
- npm run build
- npm run start
=> 192-upgrade moment

.circleci/config.yml, README.md, package-lock.json, static/scss/_icon-classes.scss
Resolves #196 
-Upgrades docker images to cimg/node14.17. We need to be using this over 14.13 which would be ideal for CMS due to a couple dependencies. We should eventually upgrade CMS. 
This is the last repo that needed to be upgraded to the new docker images.
=> 196- update docker images

README.md, package-lock.json, package.json
- Addresses #198 
_Reverts back to before the npm upgrade, adds back all recent changes (circleci docker images, readme edits) then upgrades moment with npm 6.14.15. 
This was complicated by the fact that our pattern library pulls in all CMS dependencies and we currently can't rebuild our node_modules and package-lock file without NPM errors. We are out of sync with CMS and will eventually need to be aligned back with CMS. 
-`gh pr checkout 202`
-`nvm install 14.17` ( should be npm version 6.14.15  if not `npm install -g npm@6.14.15`)
-`npm i && npm run build`
-`npm run start`
=> Remove duplicate values

.circleci/config.yml
- Addresses Failed build
This should fix the most recent failed build, so that the CMS is pulled before deployment
=> upgrade during deploy

public/nginx.conf
- Addresses #213
This ticket updates the nginx.conf file to remove ruby erb which is not supported in cflinuxfs4 according to this [PR](https://github.com/cloudfoundry/staticfile-buildpack/pull/360). This resolves the pathing/ frame element issues from removing the nginx.conf file. 
Using our own nginx.conf file with static-buildpack gives us a warning that it is not recommend. We are using our own nginx file to support the frame elements. Eventually we should move over to the nginx-buildpack or remove all of the frame elements. Here is a previous discussion on this [topic](https://github.com/fecgov/fec-proxy/issues/169). I also created a [ticket](https://github.com/fecgov/fec-pattern-library/issues/216) for this issue. 
I tested this by deploying …
=> update nginx file to remove ruby erb

.circleci/config.yml, README.md, package-lock.json
upgrade node version to be consistent with fec-cms repo: 
1. circleci/config.yml 
2. README.md
3. package-lock.json
1 developer
-run `git checkout upgrade-node-to-snyc-with-cms`
-run `rm -rf node_modules`
-run `nvm use 22.1.0` (cms and api are already running on this version. No need to install again)
-run `npm install -g npm@10.7.0` (is what is being used in circle builds)
-run `npm i` 
-run  `npm run build`
-run `npm run start`
- verify http://localhost:3000 (is UP and no errors)
=> upgrade node version
