fecgov/fec-pattern-library

.travis.yml
bin/cf_deploy.sh

App is available at https://fec-pattern-library.app.cloud.gov/

Deploy to govcloud

---

components/01-basics/_typography.html
components/02-components/buttons/basic/basic.config.json

cc @xtine I made these changes for today’s demo

Quick review and documentation

---

.circleci/config.yml
.gitignore
package-lock.json

To fix `sh: 1: cannot create public/js/main.js: Directory nonexistent` CircleCI failing.

ignore only main.js

---

README.md

Change `npm run-build-js` to `npm run build-js`

Correct run build js command

---

.circleci/config.yml

Trying to make it more like the example, the deploy in the new repo is not working

updating circle

---

README.md

Add Gemnasium badge to README file to show dependencies.

Add Gemnasium badges

---

package-lock.json
package.json

This upgrades the moment version to 2.20.1 for security reasons.

Upgrade moment version to 2.20.1

---

components/02-components/footer/footer.html

Addresses: 
https://github.com/fecgov/fec-pattern-library/issues/64
Update html in footer component in pattern ibrary

updated html for footer

---

package-lock.json
package.json

After transfer of fec-cms repo, we needed to update the fec-cms package reference to the new fecgov organization.

Updated fec-cms package reference to fecgov

---

.github/PULL_REQUEST_TEMPLATE.md

Creates a simple pull request template so that the team can complete the work faster and more consistently.
Includes:
- a summary paragraph with the option to connect an issue number
- a screenshot field
I kept it simple since this app is less complex than the `fec-cms` repo, and the changes are more visually oriented.

Adds a simple pull request template

---

package-lock.json
package.json

- Addresses #108
Update @frctl/nunjucks to ^1.0.x which will grab the latest minor version
- The latest minor version is currently 1.0.3.

Update Fractal/Nunjucks version

---

components/02-components/filter-validation/01-success-validation/README.md
components/02-components/filter-validation/01-success-validation/success-validation.config.json
components/02-components/filter-validation/01-success-validation/success-validation.html
components/02-components/filter-validation/02-error-validation/README.md
components/02-components/filter-validation/02-error-validation/error-validation.config.json
components/02-components/filter-validation/02-error-validation/error-validation.html

Adds component patterns for filter validation. This component is demonstrated in action in each filter component through a gif, but having them as a separate pattern makes them more visible, and provides a place for better explanation and history.

Add filter validation pattern to components

---

README.md

Added SNYK Vulnerability badge to pattern library

Added SNYK Vulnerability badge

---

CONTRIBUTING.md
LICENSE.md

Use FEC-wide license and contributing documents

Use FEC-wide license and contributing documents

---

bin/cf_deploy.sh
manifest.yml

- Addresses # [_130_]
_Include a summary of proposed changes._
1. add cflinuxfs2 to manifest.yml file:
path: ./docs
stack: cflinuxfs2
applications:
name: fec-pattern-library
memory: 64M
buildpack: staticfile_buildpack
2. minor changes on ./bin/cf_deploy.sh
add a comment to make sure zero-downtime-push plug-in is installed for deploy script
To test:
1. check out the branch
2. install packages and build the app to make sure everything is ok:
npm install
npm run build
npm run start
3. id everything is ok, login to cloud.gov dev space:
cf login -u <user_name> -a api.fr.cloud.gov --sso
4. run the ./bin/cf_deploy.sh script:
>> ./bin/cf_deploy.sh fec-pattern-library fec-beta-fec dev manifest.yml
deploy should have not errors.
5. also make sure circleci build is a success.
env:
FORCE_HTTPS: true

adding stack:cflinuxfs3 to manifest.yml and deploy testing.

---

README.md

verify that the vulnerability badge displays total number of vulnerabilities found on fec-pattern-library project hosted on snyk.

PAT-LIB: Add synk links

---

components/01-basics/_typography.html

This adds external links to the source fonts on the Typography page, so that it's easier to find and trace the fonts through the documentation. 
____
👋  Hello good people of the FEC! Thinking of you lately.

Adds links to font sources

---

package-lock.json
package.json

- Addresses #164 
- Pin ajv@6.2.13 to resolve snyk vulnerability
- requesting at least one-front end reviewer (@rfultz )
- check out fresh master branch
- snyk test --file=package.json (verify vulnerability exists)
- check out this PR
- remove package-lock.json, node_modules
- npm i
-  snyk test --file=package.json (verify vulnerability no longer exists)

Resolve vulerability in ajv@6.2.12

---

bin/cf_deploy.sh
manifest.yml

Resolves #171
- Reformat manifest to newer format
- Specify instances and `disk_quota` - default disk quota is 1G and the app only needs `27M` - this doesn't impact performance, just the amount of space the app itself takes up.
**Through CircleCI**
- Make your own copy of this branch (please don't commit to this branch)
- Modify the branch here to be your branch name (`feature/171-rolling-deployments`):
https://github.com/fecgov/fec-pattern-library/blob/5abf0a22eceddc851dde5dae8e2315f69c6d7038/.circleci/config.yml#L76-L81
- Push to Github, make sure build works
**Locally:**
- Install cf cli version [following this guide](https://github.com/cloudfoundry/cli/wiki/Version-Switching-Guide) or:
```
brew install cf-cli@7
brew install cf-cli@6
brew unlink cf-cli@6 && brew unlink cf-cli@7 && brew …
```

Implement rolling deployment

---

manifest.yml

- Addresses #213
This PR will upgrade the stack to cflinuxfs4.

upgrade stack to use cflinuxfs4

---

.circleci/config.yml
README.md
package-lock.json

- Addresses #218 
_Upgrades node to 18.17.1_
pull this branch
-pyenv virtualenv 3.9.16 pattern
-pyenv activate pattern
-nvm install 18.17.1
-npm i && npm run build
-npm run start
http://localhost:3000

218-upgrade node 18.17.1
